### ISSUE TITLE
修补进度条完成后什么也没有

### ISSUE THREAD

**Issue by Mubai-meng** [duzhaokun123/YAPatch#2]
修补完成后自动返回主界面，好像什么也没有发生。
如果这算修补成功的话apk去哪找？

**Comment by duzhaokun123** [comment]
这算 bug 给 录屏 log

**Comment by duzhaokun123** [comment]
![image](https://github.com/user-attachments/assets/e803b779-30c1-4d98-887d-fa542f904017)

我知道了

**Comment by duzhaokun123** [comment]
fix: 43a378ca6aa814f52c32c1e62a8244dcf38f907e
